const posts = [
    {
        id: 0,
        author: 'Anderson "Yagasaki" Marlon',
        image: '/post/broly.jpg',
        title: 'Dragon Ball Super Broly – Saiyajins estão enfurecidos no novo trailer',
        smalltitle: 'Dragon Ball Super Broly – Saiyajins estão enfurecidos no ...',
        categories: 'Animes',
        slug: 'dragon-ball-super-broly-saiyajins-estao-enfurecidos-no-novo-trailer',
        createdAt: '20/12/2018',
        createdAtExtended: '20 de Dezembro de 2018',
        ytid: 'j_GK-hYXga0',
        citation: '',
        linkCitation: '',
        description: 'Um novo trailer dublado de Dragon Ball Super Broly foi divulgado, e ele traz Goku, Vegeta e Broly enfurecidos em uma grande batalha épica.',
        body: 'Um novo trailer dublado de Dragon Ball Super Broly foi divulgado, e ele traz Goku, Vegeta e Broly enfurecidos em uma grande batalha épica.',
        body2: 'O filme se passa após o Torneio do Poder e o criador da série, Akira Toriyama, revelou que o longa deve ser focado na origem do poder dos Saiyajins. A história mostrará Broly, um Saiyajin desconhecido, que aparece diante de Goku e Vegeta, iniciando uma intensa batalha entre os três, que trilharam caminhos bastante diferentes até finalmente se encontrarem.',
        body3: 'O roteiro foi escrito pelo próprio Akira Toriyama, enquanto o design de personagens fica nas mãos de Naohiro Shintani, que substitui Tadayoshi Yamamuro, responsável pelo anime de Dragon Ball Super e pelo jogo Super Dragon Ball Heroes.',
        body4: 'Dragon Ball Super Broly estreia em 3 de janeiro de 2019 no Brasil.',
        body5: '',
    },
    {
        id: 1,
        author: 'Anderson "Yagasaki" Marlon',
        image: '/post/spiderman.jpg',
        title: 'Spiderman de PS4 incluirá traje de Tobey Maguire em atualização',
        smalltitle: 'Spiderman de PS4 incluirá traje de Tobey Maguire em atualização',
        categories: 'Games',
        slug: 'spiderman-de-ps4-incluirá-traje-de-tobey-maguire-em-atualização',
        createdAt: '20/12/2018',
        createdAtExtended: '20 de Dezembro de 2018',
        ytid: '',
        citation: '',
        linkCitation: '',
        description: 'Depois de muitos pedidos de fãs, a Insomniac Games adicionou o traje do Homem-Aranha de Tobey Maguire para o jogo Spider-Man para o PlayStation 4.',
        body: 'Depois de muitos pedidos de fãs, a Insomniac Games adicionou o traje do Homem-Aranha de Tobey Maguire para o jogo Spider-Man para o PlayStation 4. A roupa alternativa foi adicionada na atualização de hoje (20 de dezembro) do jogo.',
        body2: "We have a special holiday gift for #SpiderManPS4 players. Todays game update will include a highly requested suit. Hint: It's webbed and it's FREE for owners of Marvel's Spider-Man! — Insomniac Games (@insomniacgames) on Twitter 20 de dezembro de 2018",
        body3: 'Marvel’s Spider-Man foi lançado em 7 de setembro, exclusivamente para PlayStation 4.',
        body4: '',
        body5: '',
    },
    {
        id: 2,
        author: 'Anderson "Yagasaki" Marlon',
        image: '/post/izuku.png',
        title: 'Jump Force – Midoriya é o primeiro personagem de My Hero Academia confirmado no jogo',
        smalltitle: 'Jump Force – Midoriya é o primeiro personagem de My Hero ...',
        categories: 'Games',
        slug: 'jump-force-midoriya-é-o-primeiro-personagem-de-my-hero-academia-confirmado-no-jogo',
        createdAt: '20/12/2018',
        createdAtExtended: '20 de Dezembro de 2018',
        ytid: '',
        citation: '',
        linkCitation: '',
        description: 'Izuku Midoriya, mais conhecido como Deku em My Hero Academia, foi confirmado como um personagem jogável em Jump Force.',
        body: 'Izuku Midoriya, mais conhecido como Deku em My Hero Academia, foi confirmado como um personagem jogável em Jump Force.',
        body2: 'A informação foi revelada na edição mais recente da Weekly Shonen Jump, publicada no Japão. Deku é o primeiro personagem da franquia a chegar ao game, e seu estilo de luta consiste de socos e chutes normais, com o poder do One for All sendo ativado para ataques especiais, segundo o site Siliconera.',
        body3: 'Trunks do futuro, de Dragon Ball Z, Boa Hancock, de One Piece, e Renji Abarai, de Bleach, também foram confirmados no jogo.',
        body4: 'O jogo une diversas franquias da famosa revista japonesa Shonen Jump, como Dragon Ball, One Piece, Naruto, Bleach e Death Note, trazendo os heróis e vilões dos mangás para batalharem no mundo real.',
        body5: 'Jump Force será lançado para PC, Xbox One e PlayStation 4 no dia 15 de fevereiro de 2019.',
    },
    {
        id: 3,
        author: 'Anderson "Yagasaki" Marlon',
        image: '/post/guardian.jpg',
        title: 'League of Legends: Riot lança música e clipe para as Guardiãs Estelares',
        smalltitle: 'League of Legends: Riot lança música e clipe para as Guardiãs ...',
        categories: 'Games',
        slug: 'league-of-legends-riot-lança-música-e-clipe-para-as-guardias-estelares',
        createdAt: '22/07/2022',
        createdAtExtended: '22 de Julho de 2022',
        ytid: 'eEFVxI9lqjU',
        citation: '',
        linkCitation: '',
        description: 'Em parceria com o DJ Porter Robinson, a Riot lançou a música “Everything Goes One”, que marca o lançamento oficial das skins Guardiãs Estelares 2022 no League of Legends, Wild Rift e Legends of Runeterra.',
        body: 'Em parceria com o DJ Porter Robinson, a Riot lançou a música “Everything Goes One”, que marca o lançamento oficial das skins Guardiãs Estelares 2022 no League of Legends, Wild Rift e Legends of Runeterra.',
        body2: 'O clip mostra a grande amizade que Kai’sa e Akali, novas Guardiãs Estelares, além de também mostrar o casal Xayah e Rakan, que também ganharam versões “Redimidas” das skins no Wild Rift, o LoL Mobile.',
        body3: 'Durante o patch 12.13 de LoL, já foram lançadas as skins Guardiãs Estelares para o Ekko (com versão prestígio), Kai’sa, Nilah, Sona e Fiddlesticks. Em breve também deverão chegar no servidor as skins da Akali, Morgana, Rell, Quinn e uma versão prestígio da Syndra.',
        body4: 'No Wild Rift, as skins chegarão a partir do patch 3.3, com versões exclusivas para a Seraphine, Senna e Orianna.',
    },
    {
        id: 4,
        author: 'Anderson "Yagasaki" Marlon',
        image: '/post/dnd.jpg',
        title: 'Dungeons & Dragons: Honra Entre Rebeldes tem primeiro trailer divulgado',
        smalltitle: 'Dungeons & Dragons: Honra Entre Rebeldes tem primeiro trailer ...',
        categories: 'Movies',
        slug: 'dungeons-&-dragons-honra-entre-rebeldes-tem-primeiro-trailer-divulgado',
        createdAt: '22/07/2022',
        createdAtExtended: '22 de Julho de 2022',
        ytid: 'IiMinixSXII',
        citation: '',
        linkCitation: '',
        description: 'A Paramount revelou nesta quinta-feira (21) o primeiro trailer do filme Dungeons & Dragons: Honra Entre Rebeldes. A divulgação ocorreu durante o painel do longa na Comic-Con 2022.',
        body: 'A Paramount revelou nesta quinta-feira (21) o primeiro trailer do filme Dungeons & Dragons: Honra Entre Rebeldes. A divulgação ocorreu durante o painel do longa na Comic-Con 2022.',
        body2: 'A produção conta com a dupla Jonathan Goldstein e John Francis Daley como diretores e roteiristas, e por se tratar de uma marca da Hasbro, o longa está nas mãos de Brian Goldner e Jeremy Latchan, que representam a empresa. No elenco estão nomes conhecidos como Chris Pine (Mulher-Maravilha); Michelle Rodriguez (Velozes e Furiosos); Justice Smith (Pokémon: Detetive Pikachu); Sophia Lillis (IT-A Coisa); Rege-Jean Page (Bridgerton) e o renomado Hugh Grant (Um Lugar Chamado Notting Hill).',
        body3: 'A trama irá acompanhar um ladrão; uma bárbara; um mago e um druida que se reúnem com o objetivo de roubar um golpista que foi o responsável por eles terem sido presos. Ele fazia parte da missão, contudo, enganou a todos e pegou o que haviam saqueado para si e usou disso para se estabelecer na realeza como o Lorde de Neverwinter, como se isso não fosse o suficiente, ele está aliado a um poderoso Mago Vermelho que está tramando algo perigoso.',
        body4: 'Dungeons & Dragons: Honra Entre Rebeldes estreia em março de 2023 nos cinemas.',
    },
    {
        id: 5,
        author: 'Anderson "Yagasaki" Marlon',
        image: '/post/midnight.jpg',
        title: 'Trailer de Midnight Suns destaca habilidades e visual cintilante de Homem-Aranha',
        smalltitle: 'Trailer de Midnight Suns destaca habilidades e visual cintilante ...',
        categories: 'Games',
        slug: 'trailer-de-midnight-suns-destaca-habilidades-e-visual-cintilante-de-homem-aranha',
        createdAt: '22/07/2022',
        createdAtExtended: '22 de Julho de 2022',
        ytid: 'd-c_DwQVZhw',
        citation: '',
        linkCitation: '',
        description: 'O estúdio Firaxis revelou nesta quinta-feira (21) um trailer inédito de Midnight Suns, novo RPG tático com heróis da Marvel.',
        body: 'O estúdio Firaxis revelou nesta quinta-feira (21) um trailer inédito de Midnight Suns, novo RPG tático com heróis da Marvel.',
        body2: 'O vídeo é focado em Homem-Aranha, com destaque para habilidades que envolvem ataques com atiradores de teia, tiros rápidos e uso do ambiente. Além disso, o visual cintilante do Teioso, com as cores preto e dourado, também é destacado.',
        body3: '',
        body4: '',
    },
    {
        id: 6,
        author: 'Anderson "Yagasaki" Marlon',
        image: '/post/detroit-anime.jpg',
        title: 'Detroit Become Human: game ganhará um mangá spin-off',
        smalltitle: 'Detroit Become Human: game ganhará um mangá spin-off',
        categories: 'Animes',
        slug: 'detroit-become-human-game-ganhará-um-mangá-spin-off',
        createdAt: '22/07/2022',
        createdAtExtended: '22 de Julho de 2022',
        ytid: '',
        citation: '',
        linkCitation: '',
        description: 'Baseado no popular jogo Detroit Become Human, a editora Kadokawa está desenvolvendo um mangá spin-off chamada Detroit Become Human: Tokyo Stories.',
        body: 'Baseado no popular jogo Detroit Become Human, a editora Kadokawa está desenvolvendo um mangá spin-off chamada Detroit Become Human: Tokyo Stories.',
        body2: 'O game já superou milhões de vendas e apresenta uma trama em que as decisões do jogador irão definir o destino da cidade de Detroit e do restante do país, além de apresentar andróides com sentimentos humanos conhecidos como Divergentes. A trama do spin-off será situada numa Tóquio futurista, no ano 2038 e será publicada pela sito Comic Bridge, o mesmo responsável pela adaptação em mangá de Sex Education.',
        body3: '"Detroit Become Human" Official Manga "Detroit Become Human Tokyo Stories" starts on July 22 on the Comic Bridge website Original Story set in Tokyo of the year 2038 Image © Kadokawa, Quantic Dream, Sawatari Kazami, Sumida Moto on Twitter',
        body4: 'Detroit Become Human: Tokyo Stories será lançado dia 22 de julho no Comic Bridge.',
    },
    {
        id: 7,
        author: 'Anderson "Yagasaki" Marlon',
        image: '/post/dragon-ball.jpeg',
        title: 'Dragon Ball: série clássica estreará dublada na Crunchyroll',
        smalltitle: 'Dragon Ball: série clássica estreará dublada na Crunchyroll',
        categories: 'Animes',
        slug: 'dragon-ball-serie-clássica-estreará-dublada-na-crunchyroll',
        createdAt: '15/08/2022',
        createdAtExtended: '15 de Agosto de 2022',
        ytid: '',
        citation: '',
        linkCitation: '',
        description: 'A Crunchyroll anunciou nesta quarta-feira (10) que irá estrear a primeira série da franquia Dragon Ball em seu catálogo. A novidade se dá pelo fato da transmissão ocorrer dublada, chegando através das Quintas de Dublagem.',
        body: 'A Crunchyroll anunciou nesta quarta-feira (10) que irá estrear a primeira série da franquia Dragon Ball em seu catálogo. A novidade se dá pelo fato da transmissão ocorrer dublada, chegando através das Quintas de Dublagem.',
        body2: 'Serão disponibilizados os primeiros 31 episódios do anime, que chegarão no mesmo dia da estreia de Dragon Ball Super: Super Hero aos cinemas brasileiros. Criado por Akira Toriyama, Dragon Ball conta a história de Goku, um jovem garoto que morava nas montanhas com seu avô até que recebe a visita de uma jovem chamada Bulma. A garota estava em busca de uma das 7 esferas do dragão, sendo que uma delas estava em posse de Goku, por ser uma lembrança valiosa, o menino se recusa a dar a esfera, contudo, parte em viagem com Bulma para reunir as demais',
        body3: 'Dragon Ball irá chegar dia 18 de agosto na Crunchyroll. Vale lembrar que o anime também está disponível no Globoplay.',
        body4: '',
    },
    {
        id: 8,
        author: 'Anderson "Yagasaki" Marlon',
        image: '/post/ghost_tsushima.jpeg',
        title: 'Ghost of Tsushima: diretor deseja filmar o longa inteiramente em japonês',
        smalltitle: 'Ghost of Tsushima: diretor deseja filmar o longa inteiramente...',
        categories: 'Movies',
        slug: 'ghost-of-tsushima-diretor-deseja-filmar-o-longa-inteiramente-em-japonês',
        createdAt: '15/08/2022',
        createdAtExtended: '15 de Agosto de 2022',
        ytid: '',
        citation: '',
        linkCitation: '',
        description: 'O diretor Chad Stahelski (John Wick 4), entrevistado pela Collider durante a turnê da imprensa para Day Shift, revelou que deseja realizar uma adaptação de  Ghost of Tsushima em linguagem inteiramente japonesa.',
        body: 'O diretor Chad Stahelski (John Wick 4), entrevistado pela Collider durante a turnê da imprensa para Day Shift, revelou que deseja realizar uma adaptação de  Ghost of Tsushima em linguagem inteiramente japonesa.',
        body2: 'Bem, como se observa no título que foi originalmente inspirado nas obras do lendário cineasta Akira Kurosawa, se tornando um jogo para Playstation 4 em 2020. A história se passa no Japão do século XIII e o game oferecia ao jogador uma imersão ainda maior com a opção de áudio em japonês. Em comentários, o diretor justifica que a obra “pode se apresentar assustadora por ser uma batalha de época, fantasiosa e atemporal da mitologia entre bem e mal“. Para ele, que adora Joseph Campell entre outras influências, ter fetiche por samurai encontrados em mangás, animes e afins. Poder empurrar essa tecnologia para o público ter essa imersão no filme vai ser impressionante de se ver.',
        body3: 'Com o envolvimento da Sony, a equipe composta por japoneses vai explorar o caráter e definir aparência de Jin Sakai. Chad ama o Japão, de suas visitas que realiza  desde os 16 anos até a língua japonesa. No filme, ele espera enquanto diretor, atrair o público ocidental para a cultura oriental. Isso é algo pensando a partir destas vivências pessoais.',
        body4: 'O diretor finaliza dizendo que “se estiver certo, irá apostar em evitar erros para favorecer o visual, a ação e a história, a ponto de estimular a todos assistirem esse filme nos cinemas“. O longa de Ghost of Tsushima ainda não possuí previsão de lançamento.',
    },
    {
        id: 9,
        author: 'Anderson "Yagasaki" Marlon',
        image: '/post/rick-morty.jpg',
        title: 'Rick e Morty: divulgado trailer da 6ª temporada na HBO Max',
        smalltitle: 'Rick e Morty: divulgado trailer da 6ª temporada ...',
        categories: 'Animes',
        slug: 'rick-e-morty-divulgado-trailer-da-nova-temporada',
        createdAt: '15/08/2022',
        createdAtExtended: '15 de Agosto de 2022',
        ytid: '6Zt15L7Gy3U',
        citation: '',
        linkCitation: '',
        description: 'O HBO Max divulgou nesta quinta-feira (11) o trailer oficial para a 6ª temporada de Rick e Morty ...',
        body: 'O HBO Max divulgou nesta quinta-feira (11) o trailer oficial para a 6ª temporada de Rick e Morty.',
        body2: 'Criada pela dupla Justin Rolland e Dan Harmon, a trama acompanha Rick que vive arrastando o seu neto, Morty, em viagens interdimensionais. A série é uma produção original do Adult Swim, bloco adulto do Cartoon Network, e está com suas 5 temporadas disponíveis no HBO Max, enquanto que as primeiras se encontram no catálogo da Netflix até o dia 13 de agosto.',
        body3: 'A 6ª temporada de Rick e Morty estreia dia 4 de setembro no Adult Swim dos EUA, com transmissão simultânea no HBO Max Brasil.',
        body4: '',
    },
    {
        id: 10,
        author: 'Anderson "Yagasaki" Marlon',
        image: '/post/multiverso-adam.png',
        title: 'Adão Negro e Stripe, de Gremlins, são os próximos personagens de MultiVersus',
        smalltitle: 'Adão Negro e Stripe, de Gremlins, são os próximos ...',
        categories: 'Games',
        slug: 'adao-negro-e-stripe-de-gremlins-sao-os-proximos-personagens-de-multiversus',
        createdAt: '15/08/2022',
        createdAtExtended: '15 de Agosto de 2022',
        ytid: '',
        citation: '',
        linkCitation: '',
        description: 'O estúdio Player First Games acaba de anunciar que Adão Negro e Stripe, de Gremlins, são os próximos personagens jogáveis de MultiVersus. As informações são da Polygon.',
        body: 'O estúdio Player First Games acaba de anunciar que Adão Negro e Stripe, de Gremlins, são os próximos personagens jogáveis de MultiVersus. As informações são da Polygon.',
        body2: 'A dupla será adicionada na Temporada 1, que chega ainda hoje (15) com atualizações, modo competitivo e novos itens customizáveis. No entanto, ainda não há uma previsão de chegada para os lutadores. ',
        body3: 'Além de Adão Negro e Stripe, a Temporada 1 adicionará mais dois personagens inéditos: os protagonistas de Rick and Morty. Morty chega no dia 23 de agosto, enquanto Rick segue sem uma data concreta.',
        body4: 'MultiVersus está disponível gratuitamente em beta aberto para PS4, PS5, Xbox One, Xbox Series X|S e PC.',
    },
    {
        id: 11,
        author: 'Anderson "Yagasaki" Marlon',
        image: '/post/the-boys-quarta.png',
        title: 'Criador de The Boys confirma que produção da 4ª temporada começa em breve',
        smalltitle: 'Criador de The Boys confirma que produção da 4ª temporada ...',
        categories: 'Movies',
        slug: 'criador-de-the-boys-confirma-que-producao-da-quarta-temporada-comeca-em-breve',
        createdAt: '15/08/2022',
        createdAtExtended: '15 de Agosto de 2022',
        ytid: '',
        citation: '',
        linkCitation: '',
        description: 'Eric Kripke, criador de The Boys, divulgou uma foto indicando que as gravações da quarta temporada começam em breve ...',
        body: 'Eric Kripke, criador de The Boys, divulgou uma foto indicando que as gravações da quarta temporada começam em breve.',
        body2: 'Nas redes sociais, o showrunner publicou uma imagem no aeroporto, com as hashtags da temporada e a frase: “oi”, de Billy Bruto',
        body3: 'Detalhes sobre a nova temporada ainda não foram divulgados, mas já foi confirmado que o personagem Ryan terá mais cenas e duas novas supers serão apresentadas. E além do Eric Kripke, o Jack Quaid também havia publicado em seu Twitter que estava viajando para a gravação da Quarta temporada',
        body4: 'Além disso, o Prime Video planeja uma nova série derivada, focada na formação de jovens supers. Todas as temporadas de The Boys estão no catálogo do Amazon Prime Video. Ainda não há previsão de lançamento dos novos episódios.',
    },
    {
        id: 12,
        author: 'Anderson "Yagasaki" Marlon',
        image: '/post/csmoney.jpeg',
        title: 'Hackers utilizam CS Money para roubar mais de R$ 8 mil em skin',
        smalltitle: 'Hackers utilizam CS Money para roubar mais de R$ 8 mil ...',
        categories: 'Games',
        slug: 'hackers-utilizam-cs-money-para-roubar-mais-de-oito-mil-em-skin',
        createdAt: '16/08/2022',
        createdAtExtended: '16 de Agosto de 2022',
        ytid: '',
        citation: '',
        linkCitation: '',
        description: 'O CS Money é um dos sites de troca de skins de Counter-Strike mais conhecidos no mundo, e segundo o perfil especializado Arrow CSGO ...',
        body: 'O CS Money é um dos sites de troca de skins de Counter-Strike mais conhecidos no mundo, e segundo o perfil especializado Arrow CSGO, hackers se utilizaram de uma falha no site para roubarem mais de US$ 1,6 milhão, cerca de R$ 8,1 milhões na cotação atual, em skins de outros usuários. A empresa confirmou os roubos, mas não divulgou o valor extraviado.',
        body2: 'Até o momento, 66 contas vinculadas ao hackers foram encontradas (veja a lista aqui) e cada uma possui um valor médio de US$ 54 mil (~R$ 274 mil ) em seus inventários. De acordo com Arrow, trata-se do maior roubo em sites de skins já visto na história do CS:GO.',
        body3: 'Até a publicação desta matéria, o CS Money encontra-se fora do ar e com o seguinte aviso: “O CS Money está temporariamente fora do ar após ser alvo de um ataque hacker esta noite. Iremos consertar o problema e faremos o nosso melhor para restaurar o funcionamento normal do site. Nosso suporte está pronto para responder suas dúvidas por email”.',
        body4: 'Nas redes sociais, a plataforma disse que está focada em devolver as skins roubadas e restaurar o funcionamento normal do site. “Obrigado a todos pelo suporte, realmente agradecemos isso. No momento, nossos esforços estão focados em devolver as skins roubadas e restaurar o nosso site. Se você tiver alguma informação sobre o que aconteceu, por favor não hesite em nos contatar por DM”, escreveu o perfil.',
    },
    {
        id: 13,
        author: 'Anderson "Yagasaki" Marlon',
        image: '/post/dragonballfornite.jpg',
        title: 'Dragon Ball chega ao Fornite com skins e Kamehameha',
        smalltitle: 'Dragon Ball chega ao Fornite com skins e Kamehameha',
        categories: 'Games',
        slug: 'dragon-ball-chega-ao-fornite-com-skins-e-kamehameha',
        createdAt: '16/08/2022',
        createdAtExtended: '16 de Agosto de 2022',
        ytid: 'XiOn8wQmiAk',
        citation: '',
        linkCitation: '',
        description: 'O Fornite havia anunciado desde semana passada em seu Twitter que a parceria com o universo de Dragon Ball iria acontecer ...',
        body: 'O Fornite havia anunciado desde semana passada em seu Twitter que a parceria com o universo de Dragon Ball iria acontecer, ontem saiu a data e hoje (16) foi oficialmente lançado, trazendo skins da Bulma, Vegeta, Goku e Bill, incluindo a queda com a nuvem voadora e o famoso Kamehameha.',
        body2: 'O Kamehameha é um poder que se possui dentro do jogo através de um item e é usado para atacar inimigos. Ele é um poderoso ataque que pode ser usado em qualquer momento, mas é mais eficiente quando usado em combate de longa distância.',
        body3: 'Fortnite está gratuito e disponível em todas as plataformas.',
        body4: '',
    },
    {
        id: 14,
        author: 'Anderson "Yagasaki" Marlon',
        image: '/post/encantador-masculino-lol.jpg',
        title: 'LoL: Novo suporte encantador será de “fácil jogabilidade”, afirma rioter',
        smalltitle: 'LoL: Novo suporte encantador será de “fácil jogabilidade ...',
        categories: 'Games',
        slug: 'lol-novo-suporte-encantador-sera-de-facil-jogabilidade-afirma-rioter',
        createdAt: '16/08/2022',
        createdAtExtended: '16 de Agosto de 2022',
        ytid: '',
        citation: 'Não queremos que o nosso primeiro encantador masculino seja não jogável para muitos jogadores - via Reddit',
        linkCitation: '',
        description: 'A Riot anunciou que ainda tem três novos campeões para lançar em 2023 no League of Legends. Um deles será um Darkin ...',
        body: 'A Riot anunciou que ainda tem três novos campeões para lançar em 2023 no League of Legends. Um deles será um Darkin Assassino, outro será o K’Sante e o terceiro, ainda sem nome, será um suporte encantador masculino.',
        body2: 'Em um tópico no Reddit, um dos rioters afirmou que o novo encantador será fácil de jogar. De acordo com ele, a empresa não quer lançar dois campeões difíceis de jogar em um curto período de tempo, pois esses são para uma audiência de nicho.',
        body3: 'Apesar de ter citado o campeão suporte como o primeiro encantador masculino, é válido lembrar que o LoL tem o Tarik que também é considerado um encantador. Apesar disso, ele é o único, contra 11 encantadoras. Essa grande diferença motivou a Riot a dar uma prioridade a mais para lançar esse novo campeão. Até o momento, apenas uma imagem foi liberada sobre ele, em que três “bolas de fogo” aparecem com alguns rostinhos.',
        body4: 'Entre as outras novidades, a Riot também revelou que está trabalhando em pets para a jungle. Três novos campeões serão lançados esse ano, sendo um Darkin assassino, um um campeão de Ixtal e K’Sante, da região de Nazumah. Além disso, a Riot também anunciou detalhes do rework do Aurelion Sol, que cuspirá fogo em seu Q e voará livremente pelo mapa. O Dragão Quimtec, removido no começo do ano, retornará com novos efeitos. Novos pings chegarão ao LoL, bem como melhorias para o sistema de visão.',
    },
    {
        id: 15,
        author: 'Anderson "Yagasaki" Marlon',
        image: '/post/cw-arrow.png',
        title: 'CW: emissora conhecida pelo Arrowverse foi vendida pela Warner',
        smalltitle: 'CW: emissora conhecida pelo Arrowverse foi ...',
        categories: 'Movies',
        slug: 'cw-emissora-conhecida-pelo-arrowverse-foi-vendida-pela-warner',
        createdAt: '16/08/2022',
        createdAtExtended: '16 de Agosto de 2022',
        ytid: '',
        citation: 'Com o tempo, adotaremos uma abordagem diferente para nossa estratégia de programação da CW e aproveitaremos nossa experiência em gastar aproximadamente US$ 2 bilhões por ano em programação, atraindo e monetizando espectadores e fazendo a transição da NewsNation, nossa rede nacional de notícias a cabo, da WGN, enquanto mantendo um foco estrito no fluxo de caixa - via NewsNation',
        linkCitation: '',
        description: 'O portal Deadline informou nesta segunda-feira (15) que a emissora estadunidense CW, conhecida por ter exibido as séries ...',
        body: 'O portal Deadline informou nesta segunda-feira (15) que a emissora estadunidense CW, conhecida por ter exibido as séries do Arrowverse como The Flash e Supergirl; além de sucessos como Riverdale e Supernatural, foi vendida pela Warner Bros. Discovery para a empresa Nexstar.',
        body2: 'Contudo, a venda não é 100%, a Nexstar  confirmou que irá possuir 75% na rede enquanto as antigas proprietárias Paramount Global e Warner Bros. Discovery irão possuir 12,5% das ações. A transação será fechada formalmente no decorrer das próximas semanas. O objetivo da nova dona do canal é tornar a CW lucrativa até 2025.',
        body3: 'O  presidente e COO da Nexstar, Tom Carter, comentou que os estúdios da Paramount e Warner Bros. irão continuar produzindo conteúdo para a emissora, mas que este acordo será apenas em 2022 e 2023, após isso ele decidirá se irá manter a parceria ou não. Aparentemente, o foco da faixa etária irá mudar futuramente, a rede de TV é conhecida por exibir séries que agradam ao público jovem, da adolescências até a faixa dos 30 anos, contudo, as pesquisas mostram que pessoas de 58 anos é que mais consomem a emissora e, por isso, ela não fatura com seus programas.',
        body4: 'O objetivo de Tom é reduzir custos, além de também trazer conteúdo de sua rede de notícias chamada NewsNation para a CW. Essa compra e a divulgação da faixa etária que acompanha verdadeiramente o canal, colaboraram para o final de diversas séries nos últimos tempos, seja por cancelamentos ou sendo finalizadas de forma digna. Mais informações em breve.',
    },
    {
        id: 16,
        author: 'Anderson "Yagasaki" Marlon',
        image: '/post/squirrel.png',
        title: 'Jogo Squirrel with a Gun coloca jogador como, bem… um esquilo com uma arma',
        smalltitle: 'Jogo Squirrel with a Gun coloca jogador como, bem ...',
        categories: 'Games',
        slug: 'jogo-squirrel-with-a-gun-coloca-jogador-como-bem-um-esquilo-com-uma-arma',
        createdAt: '17/08/2022',
        createdAtExtended: '17 de Agosto de 2022',
        ytid: 'KRz15LfZjBI',
        citation: '',
        linkCitation: '',
        description: 'Rick and Morty já cumpria o dever cívico de alertar que esquilo é um bicho perigoso. Não se engane pela fofura, porque com ...',
        body: 'Rick and Morty já cumpria o dever cívico de alertar que esquilo é um bicho perigoso. Não se engane pela fofura, porque com toda certeza eles planejam dominar a Terra. Mas e se você conseguisse controlar um roedor, e ainda andasse por aí com uma… pistola?',
        body2: 'Esta é a premissa básica de Squirrel with a Gun. O jogo indie funciona como um simulador de, adivinha, um esquilo com uma arma. E o negócio é tão maluco quanto parece.',
        body3: 'Vamos admitir que, de início, a gente até pensou que fosse sacanagem. Mas num mundo onde Goat Simulator e Stray, que transformam você, respectivamente, em cabras e em um gato, existem, é CLARO que o novo jogo não só existe, como já pode até ser salvo na Steam.',
        body4: 'Squirrel with a Gun é desenvolvido pelo artista visual Dan DeEntremont. Dos gameplays que ele soltou pela internet, dá pra ver que o jogador terá toda liberdade para aloprar como quiser, quase como um GTA: Versão Esquilo.',
    },
    {
        id: 17,
        author: 'Anderson "Yagasaki" Marlon',
        image: '/post/eldenring.jpg',
        title: 'Elden Ring já vendeu mais de 16,6 milhões de cópias desde seu lançamento',
        smalltitle: 'Elden Ring já vendeu mais de 16 milhões de cópias',
        categories: 'Games',
        slug: 'elden-ring-ja-vende-mais-de-16-milhoes-de-copias-desde-seu-lancamento',
        createdAt: '18/08/2022',
        createdAtExtended: '18 de Agosto de 2022',
        ytid: '',
        citation: '',
        linkCitation: '',
        description: 'Um dos títulos mais populares do ano, Elden Ring já vendeu mais de 16,6 milhões de cópias desde seu lançamento no mês de fevereiro ...',
        body: 'Um dos títulos mais populares do ano, Elden Ring já vendeu mais de 16,6 milhões de cópias desde seu lançamento no mês de fevereiro, via GB.',
        body2: 'De acordo com o site, este marco foi conquistado no mês de junho quando o último relatório fiscal da Bandai Namco foi publicado, o que sugere que os números desde então já podem ter sido ultrapassados sem dificuldades, dado a popularidade do jogo na comunidade.',
        body3: 'Elden Ring já está disponível para Xbox Series X/S, Xbox One, PS4 & PS5, Steam Deck e PC (via Steam).',
        body4: '',
    },
]

export default posts