const posts = [
    {
        id: 0,
        image: '/post/broly.jpg',
        title: 'Dragon Ball Super Broly – Saiyajins estão enfurecidos no novo trailer',
        smalltitle: 'Dragon Ball Super Broly – Saiyajins estão enfurecidos no ...',
        categories: 'Animes',
        slug: 'dragon-ball-super-broly-saiyajins-estao-enfurecidos-no-novo-trailer',
        createdAt: '20/12/2018',
        ytid: 'j_GK-hYXga0',
        description: 'Um novo trailer dublado de Dragon Ball Super Broly foi divulgado, e ele traz Goku, Vegeta e Broly enfurecidos em uma grande batalha épica.',
        body: 'Um novo trailer dublado de Dragon Ball Super Broly foi divulgado, e ele traz Goku, Vegeta e Broly enfurecidos em uma grande batalha épica.',
        body2: 'O filme se passa após o Torneio do Poder e o criador da série, Akira Toriyama, revelou que o longa deve ser focado na origem do poder dos Saiyajins. A história mostrará Broly, um Saiyajin desconhecido, que aparece diante de Goku e Vegeta, iniciando uma intensa batalha entre os três, que trilharam caminhos bastante diferentes até finalmente se encontrarem.',
        body3: 'O roteiro foi escrito pelo próprio Akira Toriyama, enquanto o design de personagens fica nas mãos de Naohiro Shintani, que substitui Tadayoshi Yamamuro, responsável pelo anime de Dragon Ball Super e pelo jogo Super Dragon Ball Heroes.',
        body4: 'Dragon Ball Super Broly estreia em 3 de janeiro de 2019 no Brasil.',
        body5: '',
    },
    {
        id: 1,
        image: '/post/spiderman.jpg',
        title: 'Spiderman de PS4 incluirá traje de Tobey Maguire em atualização',
        smalltitle: 'Spiderman de PS4 incluirá traje de Tobey Maguire em atualização',
        categories: 'Games',
        slug: 'spiderman-de-ps4-incluirá-traje-de-tobey-maguire-em-atualização',
        createdAt: '20/12/2018',
        ytid: '',
        description: 'Depois de muitos pedidos de fãs, a Insomniac Games adicionou o traje do Homem-Aranha de Tobey Maguire para o jogo Spider-Man para o PlayStation 4.',
        body: 'Depois de muitos pedidos de fãs, a Insomniac Games adicionou o traje do Homem-Aranha de Tobey Maguire para o jogo Spider-Man para o PlayStation 4. A roupa alternativa foi adicionada na atualização de hoje (20 de dezembro) do jogo.',
        body2: "We have a special holiday gift for #SpiderManPS4 players. Todays game update will include a highly requested suit. Hint: It's webbed and it's FREE for owners of Marvel's Spider-Man! — Insomniac Games (@insomniacgames) on Twitter 20 de dezembro de 2018",
        body3: 'Marvel’s Spider-Man foi lançado em 7 de setembro, exclusivamente para PlayStation 4.',
        body4: '',
        body5: '',
    },
    {
        id: 2,
        image: '/post/izuku.png',
        title: 'Jump Force – Midoriya é o primeiro personagem de My Hero Academia confirmado no jogo',
        smalltitle: 'Jump Force – Midoriya é o primeiro personagem de My Hero ...',
        categories: 'Games',
        slug: 'jump-force-midoriya-é-o-primeiro-personagem-de-my-hero-academia-confirmado-no-jogo',
        createdAt: '20/12/2018',
        ytid: '',
        description: 'Izuku Midoriya, mais conhecido como Deku em My Hero Academia, foi confirmado como um personagem jogável em Jump Force.',
        body: 'Izuku Midoriya, mais conhecido como Deku em My Hero Academia, foi confirmado como um personagem jogável em Jump Force.',
        body2: 'A informação foi revelada na edição mais recente da Weekly Shonen Jump, publicada no Japão. Deku é o primeiro personagem da franquia a chegar ao game, e seu estilo de luta consiste de socos e chutes normais, com o poder do One for All sendo ativado para ataques especiais, segundo o site Siliconera.',
        body3: 'Trunks do futuro, de Dragon Ball Z, Boa Hancock, de One Piece, e Renji Abarai, de Bleach, também foram confirmados no jogo.',
        body4: 'O jogo une diversas franquias da famosa revista japonesa Shonen Jump, como Dragon Ball, One Piece, Naruto, Bleach e Death Note, trazendo os heróis e vilões dos mangás para batalharem no mundo real.',
        body5: 'Jump Force será lançado para PC, Xbox One e PlayStation 4 no dia 15 de fevereiro de 2019.',
    },
    {
        id: 3,
        image: '/post/guardian.jpg',
        title: 'League of Legends: Riot lança música e clipe para as Guardiãs Estelares',
        smalltitle: 'League of Legends: Riot lança música e clipe para as Guardiãs ...',
        categories: 'Games',
        slug: 'league-of-legends-riot-lança-música-e-clipe-para-as-guardias-estelares',
        createdAt: '22/07/2022',
        ytid: 'eEFVxI9lqjU',
        description: 'Em parceria com o DJ Porter Robinson, a Riot lançou a música “Everything Goes One”, que marca o lançamento oficial das skins Guardiãs Estelares 2022 no League of Legends, Wild Rift e Legends of Runeterra.',
        body: 'Em parceria com o DJ Porter Robinson, a Riot lançou a música “Everything Goes One”, que marca o lançamento oficial das skins Guardiãs Estelares 2022 no League of Legends, Wild Rift e Legends of Runeterra.',
        body2: 'O clip mostra a grande amizade que Kai’sa e Akali, novas Guardiãs Estelares, além de também mostrar o casal Xayah e Rakan, que também ganharam versões “Redimidas” das skins no Wild Rift, o LoL Mobile.',
        body3: 'Durante o patch 12.13 de LoL, já foram lançadas as skins Guardiãs Estelares para o Ekko (com versão prestígio), Kai’sa, Nilah, Sona e Fiddlesticks. Em breve também deverão chegar no servidor as skins da Akali, Morgana, Rell, Quinn e uma versão prestígio da Syndra.',
        body4: 'No Wild Rift, as skins chegarão a partir do patch 3.3, com versões exclusivas para a Seraphine, Senna e Orianna.',
    },
    {
        id: 4,
        image: '/post/dnd.jpg',
        title: 'Dungeons & Dragons: Honra Entre Rebeldes tem primeiro trailer divulgado',
        smalltitle: 'Dungeons & Dragons: Honra Entre Rebeldes tem primeiro trailer ...',
        categories: 'Movies',
        slug: 'dungeons-&-dragons-honra-entre-rebeldes-tem-primeiro-trailer-divulgado',
        createdAt: '22/07/2022',
        ytid: 'eEFVxI9lqjU',
        description: 'A Paramount revelou nesta quinta-feira (21) o primeiro trailer do filme Dungeons & Dragons: Honra Entre Rebeldes. A divulgação ocorreu durante o painel do longa na Comic-Con 2022.',
        body: 'A Paramount revelou nesta quinta-feira (21) o primeiro trailer do filme Dungeons & Dragons: Honra Entre Rebeldes. A divulgação ocorreu durante o painel do longa na Comic-Con 2022.',
        body2: 'A produção conta com a dupla Jonathan Goldstein e John Francis Daley como diretores e roteiristas, e por se tratar de uma marca da Hasbro, o longa está nas mãos de Brian Goldner e Jeremy Latchan, que representam a empresa. No elenco estão nomes conhecidos como Chris Pine (Mulher-Maravilha); Michelle Rodriguez (Velozes e Furiosos); Justice Smith (Pokémon: Detetive Pikachu); Sophia Lillis (IT-A Coisa); Rege-Jean Page (Bridgerton) e o renomado Hugh Grant (Um Lugar Chamado Notting Hill).',
        body3: 'A trama irá acompanhar um ladrão; uma bárbara; um mago e um druida que se reúnem com o objetivo de roubar um golpista que foi o responsável por eles terem sido presos. Ele fazia parte da missão, contudo, enganou a todos e pegou o que haviam saqueado para si e usou disso para se estabelecer na realeza como o Lorde de Neverwinter, como se isso não fosse o suficiente, ele está aliado a um poderoso Mago Vermelho que está tramando algo perigoso.',
        body4: 'Dungeons & Dragons: Honra Entre Rebeldes estreia em março de 2023 nos cinemas.',
    },
    {
        id: 5,
        image: '/post/midnight.jpg',
        title: 'Trailer de Midnight Suns destaca habilidades e visual cintilante de Homem-Aranha',
        smalltitle: 'Trailer de Midnight Suns destaca habilidades e visual cintilante ...',
        categories: 'Games',
        slug: 'trailer-de-midnight-suns-destaca-habilidades-e-visual-cintilante-de-homem-aranha',
        createdAt: '22/07/2022',
        ytid: 'd-c_DwQVZhw',
        description: 'O estúdio Firaxis revelou nesta quinta-feira (21) um trailer inédito de Midnight Suns, novo RPG tático com heróis da Marvel.',
        body: 'O estúdio Firaxis revelou nesta quinta-feira (21) um trailer inédito de Midnight Suns, novo RPG tático com heróis da Marvel.',
        body2: 'O vídeo é focado em Homem-Aranha, com destaque para habilidades que envolvem ataques com atiradores de teia, tiros rápidos e uso do ambiente. Além disso, o visual cintilante do Teioso, com as cores preto e dourado, também é destacado.',
        body3: '',
        body4: '',
    },
    {
        id: 6,
        image: '/post/detroit-anime.jpg',
        title: 'Detroit Become Human: game ganhará um mangá spin-off',
        smalltitle: 'Detroit Become Human: game ganhará um mangá spin-off',
        categories: 'Mangá',
        slug: 'detroit-become-human-game-ganhará-um-mangá-spin-off',
        createdAt: '22/07/2022',
        ytid: '',
        description: 'Baseado no popular jogo Detroit Become Human, a editora Kadokawa está desenvolvendo um mangá spin-off chamada Detroit Become Human: Tokyo Stories.',
        body: 'Baseado no popular jogo Detroit Become Human, a editora Kadokawa está desenvolvendo um mangá spin-off chamada Detroit Become Human: Tokyo Stories.',
        body2: 'O game já superou milhões de vendas e apresenta uma trama em que as decisões do jogador irão definir o destino da cidade de Detroit e do restante do país, além de apresentar andróides com sentimentos humanos conhecidos como Divergentes. A trama do spin-off será situada numa Tóquio futurista, no ano 2038 e será publicada pela sito Comic Bridge, o mesmo responsável pela adaptação em mangá de Sex Education.',
        body3: '"Detroit Become Human" Official Manga "Detroit Become Human Tokyo Stories" starts on July 22 on the Comic Bridge website Original Story set in Tokyo of the year 2038 Image © Kadokawa, Quantic Dream, Sawatari Kazami, Sumida Moto on Twitter',
        body4: 'Detroit Become Human: Tokyo Stories será lançado dia 22 de julho no Comic Bridge.',
    },
]

export default posts